version: '3.8'

services:
  # Serviço da Aplicação (PHP)
  app:
    build: .
    container_name: techfix_app
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
      - techfix_network

  # Serviço do Banco de Dados (MySQL)
  db:
    image: mysql:8.0
    container_name: techfix_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Carrega as variáveis do seu arquivo .env para configurar o banco
    env_file:
      - .env
    # Mapeamento explícito caso o .env use nomes diferentes das vars do MySQL
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: root
    networks:
      - techfix_network

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: techfix_swagger
    restart: always
    ports:
      - "8081:8080" # Acessaremos em localhost:8081
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ./public:/openapi # Mapeia a pasta public para o swagger ler o arquivo
    networks:
      - techfix_network

networks:
  techfix_network:
    driver: bridge

volumes:
  db_data: